module.exports={
    PRODUCT_COLLECTION:'product',
    ADMIN_COLLECTION:'admin_login',
    ADD_DEALER_COLLECTION:'add_dealer',
    DEALER_DETAILS_COLLECTION:'dealer_details',
    DEALER_COLLECTION:'dealer_login',
    ADD_PRODUCT_COLLECTION:'products',
    USER_COLLECTION:'user',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order'
}